### ISSUE TITLE
Configure Illinois Miscanthus run  

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/biocro_regional#1]
* [x] 15 years 
* [x] use NARR 0.25 x 3 hourly inputs
* [x] ensemble of 500 runs parameterized using PEcAn (PFT = misp)
* [x] define domain (@taolin1)  [Midwest_boundary.csv](https://gist.githubusercontent.com/dlebauer/b2a0373cd5b428d07c8b/raw/527552d31c980fc71d44d0976f09d84c828606ea/Midwest_boundary.csv). 
 * [x] extract elevation for each point (optional)
 * [x] insert into BETYdb

**Comment by dlebauer** [comment]
@taolin1 could you give me either a bounding box, polygon, or list of states to be evaluated in the analysis?

... easiest if specified as a PostGIS geom, like this one for champaign county, but a table of lat/lon pairs would be okay (I have a [crude method for assigning elevation and generating insert statements here](http://rpubs.com/dlebauer/postgis_geometry)).

```sql
ST_SetSRID (
	ST_MakePolygon (
		ST_GeomFromText (
			'LINESTRING(
             -88.4646835327148 40.2789344787598 231.220825195312,-88.4589538574219 40.3877983093262 225.489318847656,
             -88.0120468139648 40.3935241699219 226.048049926758,-88.0063171386719 40.376335144043 227.089981079102,
             -87.9318313598633 40.37060546875 222.345275878906,-87.9318313598633 40.2216377258301 224.113204956055,
             -87.9432907104492 40.2216377258301 221.840393066406,-87.9432907104492 39.8721351623535 218.766220092773,
             -88.4704132080078 39.8721351623535 204.154159545898,-88.4761428833008 40.2101783752441 223.626693725586,
             -88.4646835327148 40.2159080505371 235.470901489258,-88.4646835327148 40.2789344787598 231.220825195312,
             -88.4646835327148 40.2789344787598 231.220825195312)'
		)
	),
	4326
)
```

**Comment by taolin1** [comment]
Hi David,

I will give a try for the geom. The region for the analysis would be Midwestern area, including North Dakota, South Dakota, Nebraska, Kansas, Minnesota, Iowa, Missouri, Wisconsin, Illinois, Indiana, Ohio and Michigan.

Regards,
Tao

On Mar 18, 2015, at 4:23 PM, David LeBauer <notifications@github.com<mailto:notifications@github.com>> wrote:


@taolin1<https://github.com/taolin1> could you give me either a bounding box, polygon, or list of states to be evaluated in the analysis?

... easiest if specified as a PostGIS geom, like this one for champaign county, but a table of lat/lon pairs would be okay (I have a crude method for assigning elevation and generating insert statements here<http://rpubs.com/dlebauer/postgis_geometry>).

ST_SetSRID (
    ST_MakePolygon (
        ST_GeomFromText (
            'LINESTRING(
             -88.4646835327148 40.2789344787598 231.220825195312,-88.4589538574219 40.3877983093262 225.489318847656,
             -88.0120468139648 40.3935241699219 226.048049926758,-88.0063171386719 40.376335144043 227.089981079102,
             -87.9318313598633 40.37060546875 222.345275878906,-87.9318313598633 40.2216377258301 224.113204956055,
             -87.9432907104492 40.2216377258301 221.840393066406,-87.9432907104492 39.8721351623535 218.766220092773,
             -88.4704132080078 39.8721351623535 204.154159545898,-88.4761428833008 40.2101783752441 223.626693725586,
             -88.4646835327148 40.2159080505371 235.470901489258,-88.4646835327148 40.2789344787598 231.220825195312,
             -88.4646835327148 40.2789344787598 231.220825195312)'
        )
    ),
    4326
)

**Comment by dlebauer** [comment]
@taolin1 do you want a box, or all states?

**Comment by taolin1** [comment]
David,

Hao Hu, a Ph.D. student at the CyberGIS center, helped me with the boundary data of 12 midwestern states. Please see attached to see if that is what you need.

I am not sure the difference between box and all states. The boundary data is derived from the individual state.

Hao, correct me if I am wrong.
Regards,
Tao

On Mar 18, 2015, at 6:58 PM, David LeBauer <notifications@github.com<mailto:notifications@github.com>> wrote:


@taolin1<https://github.com/taolin1> do you want a box, or all states?

**Comment by dlebauer** [comment]
github issues don't take attachments, though 'gists' (https://gist.github.com/) are a good place to put text files and bits of code

**Comment by taolin1** [comment]
Hi Tao and David,

Just to clarify that the boundary coordinates are generated from one single merged polygon of twelve Midwest states. So it is a closed polygon geometry.

Best,
Hao

On Mar 18, 2015, at 7:03 PM, Lin, Tao <taolin1@illinois.edu<mailto:taolin1@illinois.edu>> wrote:

David,

Hao Hu, a Ph.D. student at the CyberGIS center, helped me with the boundary data of 12 midwestern states. Please see attached to see if that is what you need.

I am not sure the difference between box and all states. The boundary data is derived from the individual state.

Hao, correct me if I am wrong.
Regards,
Tao

On Mar 18, 2015, at 6:58 PM, David LeBauer <notifications@github.com<mailto:notifications@github.com>> wrote:


@taolin1<https://github.com/taolin1> do you want a box, or all states?

—
Reply to this email directly or view it on GitHub<https://github.com/ebimodeling/biocro_regional/issues/1#issuecomment-83227957>.

<Midwest.csv>

**Comment by dlebauer** [comment]
Thanks - I've moved them to [Midwest_boundary.csv](https://gist.githubusercontent.com/dlebauer/b2a0373cd5b428d07c8b/raw/527552d31c980fc71d44d0976f09d84c828606ea/Midwest_boundary.csv).
