### ISSUE TITLE
Compare Miscanthus parameters to defaults

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/biocro_regional#9]
* [x] Vmax estimated by meta-analysis is much smaller than default of 50.
* [x] check other parameters as well
* [x] add new parameters that are used by salix PFT but not (yet) by miscanthus 
 * [x] quantum efficiency 
 * [x] chi_leaf

**Comment by dlebauer** [comment]
As discussed in ebimodeling/Miscanthus_water_use_manuscript#18:

Fernando's paper ([Miguez et al 2009](http://onlinelibrary.wiley.com/doi/10.1111/j.1757-1707.2009.01019.x/epdf)) used Vmax = 39 and ...

![image](https://cloud.githubusercontent.com/assets/464871/8460747/d9317cbc-1fec-11e5-9a5b-cecffc8b70d9.png)

**Comment by UrsulaRuiz** [comment]
Hi Dave,
In the figure I showed in the last meeting I used 39 for Vmax.

On Wed, Jul 1, 2015 at 12:30 PM, David LeBauer <notifications@github.com>
wrote:

> As discussed in ebimodeling/Miscanthus_water_use_manuscript#18
> <https://github.com/ebimodeling/Miscanthus_water_use_manuscript/issues/18>
> :
>
> Fernando's paper (Miguez et al 2009
> <http://onlinelibrary.wiley.com/doi/10.1111/j.1757-1707.2009.01019.x/epdf>)
> used Vmax = 39 and ...
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/464871/8460747/d9317cbc-1fec-11e5-9a5b-cecffc8b70d9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebimodeling/biocro_regional/issues/9#issuecomment-117758762>
> .
>



-- 
Dr. Ursula Ruiz-Vera
Postdoctoral Research Associate

Carl R. Woese Institute for Genomic Biology,
University of Illinois at Urbana-Champaign

1206 W. Gregory Drive, Room 1400
Urbana, Illinois 61801
ruizver1@illinois.edu
+407-694-6405

**Comment by dlebauer** [comment]
@UrsulaRuiz are you otherwise using defaults?

**Comment by UrsulaRuiz** [comment]
Yes, I am using defaults. The values I entered before the run are: the type
of soil, the day of emerge, day for the peak of yield, the initial rhizome .

I still need to change the Tp1 tp2 in phenology.

On Thu, Jul 2, 2015 at 9:27 AM, David LeBauer <notifications@github.com>
wrote:

> @UrsulaRuiz <https://github.com/UrsulaRuiz> are you otherwise using
> defaults?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebimodeling/biocro_regional/issues/9#issuecomment-118049943>
> .
>



-- 
Dr. Ursula Ruiz-Vera
Postdoctoral Research Associate

Carl R. Woese Institute for Genomic Biology,
University of Illinois at Urbana-Champaign

1206 W. Gregory Drive, Room 1400
Urbana, Illinois 61801
ruizver1@illinois.edu
+407-694-6405

**Comment by dlebauer** [comment]
What values are you using for
* day of emergence
* day for the peak of yield (and what parameter is this?)
* initial rhizome .
* Tp1, tp2,

?

**Comment by UrsulaRuiz** [comment]
They are specified in the Miscanthus_Manuscript.RMd file in the inst folder
which is inside the Miscanthus_water_use

The values are from the energy farm data

On Thu, Jul 2, 2015 at 9:43 AM, David LeBauer <notifications@github.com>
wrote:

> What values are you using for
> * day of emergence
> * day for the peak of yield (and what parameter is this?)
> * initial rhizome .
> * Tp1, tp2,
>
> ?
>
> On Thu, Jul 2, 2015 at 9:36 AM, UrsulaRuiz <notifications@github.com>
> wrote:
>
> > Yes, I am using defaults. The values I entered before the run are: the
> type
> > of soil, the day of emerge, day for the peak of yield, the initial
> rhizome
> > .
> >
> > I still need to change the Tp1 tp2 in phenology.
> >
> > On Thu, Jul 2, 2015 at 9:27 AM, David LeBauer <notifications@github.com>
> > wrote:
> >
> > > @UrsulaRuiz <https://github.com/UrsulaRuiz> are you otherwise using
> > > defaults?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ebimodeling/biocro_regional/issues/9#issuecomment-118049943
> > >
> >
> > > .
> > >
> >
> >
> >
> > --
> > Dr. Ursula Ruiz-Vera
> > Postdoctoral Research Associate
> >
> > Carl R. Woese Institute for Genomic Biology,
> > University of Illinois at Urbana-Champaign
> >
> > 1206 W. Gregory Drive, Room 1400
> > Urbana, Illinois 61801
> > ruizver1@illinois.edu
> > +407-694-6405
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ebimodeling/biocro_regional/issues/9#issuecomment-118052065
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebimodeling/biocro_regional/issues/9#issuecomment-118054930>
> .
>



-- 
Dr. Ursula Ruiz-Vera
Postdoctoral Research Associate

Carl R. Woese Institute for Genomic Biology,
University of Illinois at Urbana-Champaign

1206 W. Gregory Drive, Room 1400
Urbana, Illinois 61801
ruizver1@illinois.edu
+407-694-6405

**Comment by dlebauer** [comment]
both the definition of newphenoParms and its use are commented out ... are you planning to use these values?

```r
#newphenoParms <- phenoParms(tp1=525, tp2=1226, tp3=1927, tp4=3500, tp5=3600, tp6=4000, kRhizome1=-0.1, kRhizome2=-0.08)
...
res09 <- BioGro(WetDat=weather09, iRhizome=iRhizome, day1=day1, dayn=dayn, photoControl=newphotoparameters, soilControl = soilparameters_565B)#, phenoControl=newphenoParms)
```

**Comment by UrsulaRuiz** [comment]
I need to change tp1 and tp2 in each year.

On Thu, Jul 2, 2015 at 11:52 AM, David LeBauer <notifications@github.com>
wrote:

> both the definition of newphenoParms and its use are commented out ... are
> you planning to use these values?
>
> #newphenoParms <- phenoParms(tp1=525, tp2=1226, tp3=1927, tp4=3500, tp5=3600, tp6=4000, kRhizome1=-0.1, kRhizome2=-0.08)...res09 <- BioGro(WetDat=weather09, iRhizome=iRhizome, day1=day1, dayn=dayn, photoControl=newphotoparameters, soilControl = soilparameters_565B)#, phenoControl=newphenoParms)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebimodeling/biocro_regional/issues/9#issuecomment-118091461>
> .
>



-- 
Dr. Ursula Ruiz-Vera
Postdoctoral Research Associate

Carl R. Woese Institute for Genomic Biology,
University of Illinois at Urbana-Champaign

1206 W. Gregory Drive, Room 1400
Urbana, Illinois 61801
ruizver1@illinois.edu
+407-694-6405

**Comment by dlebauer** [comment]
How do you determine tp1 and tp2?

**Comment by djaiswal** [comment]
@dlebauer 
We are adjusting them empirically to match observations of LAI growth observed at the Efarm.
Even if we do not change tp1 and tp2, final yields estimates are still acceptable. we plan to change them only to match pattern of LAI growth.
There should not be any need to change them if  you are, at this moment, interested in final yield.
